// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ibanking.Strings {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ibanking.Strings.strings", typeof(strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string noConnection {
            get {
                return ResourceManager.GetString("noConnection", resourceCulture);
            }
        }
        
        internal static string noConnectionError {
            get {
                return ResourceManager.GetString("noConnectionError", resourceCulture);
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string Acceso {
            get {
                return ResourceManager.GetString("Acceso", resourceCulture);
            }
        }
        
        internal static string OtherInfo {
            get {
                return ResourceManager.GetString("OtherInfo", resourceCulture);
            }
        }
        
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string doLogin {
            get {
                return ResourceManager.GetString("doLogin", resourceCulture);
            }
        }
        
        internal static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string RequiredUsernameAndPassword {
            get {
                return ResourceManager.GetString("RequiredUsernameAndPassword", resourceCulture);
            }
        }
        
        internal static string Cuenta {
            get {
                return ResourceManager.GetString("Cuenta", resourceCulture);
            }
        }
        
        internal static string Estatus {
            get {
                return ResourceManager.GetString("Estatus", resourceCulture);
            }
        }
        
        internal static string Disponible {
            get {
                return ResourceManager.GetString("Disponible", resourceCulture);
            }
        }
        
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        internal static string lblFechaProceso {
            get {
                return ResourceManager.GetString("lblFechaProceso", resourceCulture);
            }
        }
        
        internal static string CuentasAhorro {
            get {
                return ResourceManager.GetString("CuentasAhorro", resourceCulture);
            }
        }
        
        internal static string Resumen {
            get {
                return ResourceManager.GetString("Resumen", resourceCulture);
            }
        }
        
        internal static string Prestamo {
            get {
                return ResourceManager.GetString("Prestamo", resourceCulture);
            }
        }
        
        internal static string Monto {
            get {
                return ResourceManager.GetString("Monto", resourceCulture);
            }
        }
        
        internal static string Vencido {
            get {
                return ResourceManager.GetString("Vencido", resourceCulture);
            }
        }
        
        internal static string Certificado {
            get {
                return ResourceManager.GetString("Certificado", resourceCulture);
            }
        }
        
        internal static string Prestamos {
            get {
                return ResourceManager.GetString("Prestamos", resourceCulture);
            }
        }
        
        internal static string Certificados {
            get {
                return ResourceManager.GetString("Certificados", resourceCulture);
            }
        }
        
        internal static string Aportacion {
            get {
                return ResourceManager.GetString("Aportacion", resourceCulture);
            }
        }
        
        internal static string Aportaciones {
            get {
                return ResourceManager.GetString("Aportaciones", resourceCulture);
            }
        }
    }
}
